swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /getData:
    get:
      operationId: "data.getData"
      tags:
        - "Data"
      summary: "Get data"
      description: "Read the list of row"
      responses:
        200:
          description: "Successful read data list operation"
          schema:
            type: "array"
            items:
              properties:
                checkingaccountid:
                  type: "string"
                accountname:
                  type: "string"
                balance:
                  type: "string"
  /postData:
    post:
      operationId: "data.postData"
      tags:
        - "Data"
      summary: "Create data with the 3 fields"
      description: "Create data with 3  fields"
      parameters:
        - name: person
          in: body
          description: Data to create
          required: True
          schema:
            type: object
            properties:
              CHECKINGACCOUNTID:
                type: number
                description: Id of data to create
              ACCOUNTNAME:
                type: string
                description: Name of data to create
              BALANCE:
                type: number
                description: balance
      responses:
        200:
          description: "Successful create operation"
          schema:
            type: "array"
            items:
              properties:
                checkingaccountid:
                  type: "string"
                accountname:
                  type: "string"
                balance:
                  type: "string"
  /deleteData:
    post:
      operationId: "data.deleteData"
      tags:
        - "Data"
      summary: "Delete data based on id"
      description: "Delete from the list of data"
      parameters:
        - name: person
          in: body
          description: Data to delete
          required: True
          schema:
            type: object
            properties:
              CHECKINGACCOUNTID:
                type: number
                description: Id of data to delete
              ACCOUNTNAME:
                type: string
                description: Name of data to delete
              BALANCE:
                type: number
                description: balance
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                checkingaccountid:
                  type: "string"
                accountname:
                  type: "string"
                balance:
                  type: "string"