CREATE TABLE temperature (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    temperature INTEGER DEFAULT 25 NOT NULL,
    timestamp DATETIME NOT NULL,
    tocloud INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE door (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    door_open INTEGER DEFAULT 0 NOT NULL,
    timestamp DATETIME NOT NULL,
    tocloud INTEGER DEFAULT 0 NOT NULL
);