swagger: "2.0"
info:
  description: This is the swagger file for raspiberry pi with object detection
  version: "1.0.0"
  title: Swagger REST api doc for raspiberry pi with object detection
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/objdet_raspi/api"

# Paths supported by the server application
paths:
  /get-current-items:
    get:
      operationId: "objdet_raspi_restapi.get_current_items"
      tags:
        - "Item Table"
      summary: "Retrieve item data stored in database"
      description: "Retrieve item data stored in database"
      responses:
        200:
          description: "Successfully get item data"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "number"
                banana:
                  type: "number"
                apple:
                  type: "number"
                sandwich:
                  type: "number"
                orange:
                  type: "number"
                broccoli:
                  type: "number"
                carrot:
                  type: "number"
                hot_dog:
                  type: "number"
                pizza:
                  type: "number"
                donut:
                  type: "number"
                cake:
                  type: "number"
                timestamp:
                  type: "string"

  /get-all-items:
    get:
      operationId: "objdet_raspi_restapi.get_all_items"
      tags:
        - "Item Table"
      summary: "Retrieve item data stored in database"
      description: "Retrieve item data stored in database"
      responses:
        200:
          description: "Successfully get item data"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "number"
                banana:
                  type: "number"
                apple:
                  type: "number"
                sandwich:
                  type: "number"
                orange:
                  type: "number"
                broccoli:
                  type: "number"
                carrot:
                  type: "number"
                hot_dog:
                  type: "number"
                pizza:
                  type: "number"
                donut:
                  type: "number"
                cake:
                  type: "number"
                timestamp:
                  type: "string"

  /get-items-range:
    get:
      operationId: "objdet_raspi_restapi.get_items_range"
      tags:
        - "Item Table"
      summary: "Retrieve item data stored in database"
      description: "Retrieve item data stored in database"
      parameters:
        - name: "from_date"
          in: "query"
          description: "a dateStamp that can be understood by SQLite"
          required: true
          type: "string"
        - name: "to_date"
          in: "query"
          description: "a dateStamp that can be understood by SQLite"
          required: true
          type: "string"
      responses:
        200:
          description: "Successfully get item data"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "number"
                banana:
                  type: "number"
                apple:
                  type: "number"
                sandwich:
                  type: "number"
                orange:
                  type: "number"
                broccoli:
                  type: "number"
                carrot:
                  type: "number"
                hot_dog:
                  type: "number"
                pizza:
                  type: "number"
                donut:
                  type: "number"
                cake:
                  type: "number"
                timestamp:
                  type: "string"

  /get-snapshot:
    get:
      operationId: "objdet_raspi_restapi.get_snapshot"
      tags:
        - "Image"
      responses:
        '200':           # Response
          description: OK

  /get-predicted-snapshot:
    get:
      operationId: "objdet_raspi_restapi.get_predicted_snapshot"
      tags:
        - "Image"
      responses:
        '200':           # Response
          description: base64 img + item dict
